version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-competence
    restart: always
    environment:
      MYSQL_DATABASE: competencedb
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password_here
      MYSQL_ROOT_PASSWORD: your_password_here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-competence
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: your_password_here
    ports:
      - "8082:80"

  competence-service:
    image: competence-service:latest
    container_name: competence-service
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/competencedb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: your_password_here
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_APPLICATION_NAME: competence-service
      SPRINGDOC_API_DOCS_PATH: /v3/api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html

volumes:
  mysql_data:
