server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: competence-service
          uri: lb://competence-service
          predicates:
            - Path=/competence/**
        - id: rendu-service
          uri: lb://rendu-service
          predicates:
            - Path=/rendu/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

